### PR TITLE
Improved docs Update README.md

### PR DESCRIPTION
**Pull request by pranjalbansal1916**
Added a personalized message so that customers could be more attached

I hope you like it 

Regards 
Pranjal Bansal

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Please tag this garbage as [invalid] so it does not count for the user's Hacktoberfest contributions.

**Comment by jocelynj** [comment]
@ThiefMaster: I've received several PR on this repository with invalid changes, and I've just closed the PR with a message about Spam. Should I also change the title message to [invalid] ?

**Comment by ThiefMaster** [comment]
No, just add a label "invalid" to the PR (using github's issue/pr labels on the right side). This makes the PR ineligible for hackoberfest.

**Comment by jocelynj** [comment]
Thanks!

**Pull request closed without merging**
